In [16]:
import torch
import numpy as np

In [17]:
a=torch.FloatTensor([1,2])
n=np.array([[1,2],[3,4],[5,6]])

In [19]:
print(a)
print(n)

tensor([1., 2.])
[[1 2]
 [3 4]
 [5 6]]


In [20]:
a=torch.from_numpy(n)
a

tensor([[1, 2],
        [3, 4],
        [5, 6]], dtype=torch.int32)

In [23]:
a.numpy()

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
a

tensor([[1, 2],
        [3, 4],
        [5, 6]], dtype=torch.int32)

In [26]:
a=torch.FloatTensor([1,2])
n=np.array([[1,2],[3,4],[5,6]])
a.size()

torch.Size([2])

In [27]:
x=a+n
x

tensor([[2., 4.],
        [4., 6.],
        [6., 8.]], dtype=torch.float64)