# Pytorch Tutorial

In [1]:
import torch
import numpy as np

### 1. Numpy Compatibility

In [2]:
#pytorch is really similar with numpy
#Could convert numpy to torch or torch to numpy easily
torch_tensor=torch.FloatTensor([1,2])
numpy_array=np.array([[1,2],[3,4],[5,6]])

In [3]:
print(torch_tensor)
print(numpy_array)

tensor([1., 2.])
[[1 2]
 [3 4]
 [5 6]]


In [4]:
torch_tensor=torch.from_numpy(numpy_array)
torch_tensor

tensor([[1, 2],
        [3, 4],
        [5, 6]], dtype=torch.int32)

In [5]:
torch_tensor.numpy()

array([[1, 2],
       [3, 4],
       [5, 6]])

### 2. Get Shape

In [6]:
#We can use size() or shape. It will come out with the same result
torch_tensor.size()

torch.Size([3, 2])

In [7]:
torch_tensor.shape

torch.Size([3, 2])

### 3. Type-Casting

In [8]:
#Just type any type that we want and add () at the end
#This code is from float to int
torch_tensor.int()

tensor([[1, 2],
        [3, 4],
        [5, 6]], dtype=torch.int32)

### 4. Inplace

In [9]:
#We can use _ for inplace=True. (same as pandas.drop(inplace=True))
torch_tensor.mul(torch_tensor)
torch_tensor

tensor([[1, 2],
        [3, 4],
        [5, 6]], dtype=torch.int32)

In [10]:
torch_tensor.mul_(torch_tensor)
torch_tensor

tensor([[ 1,  4],
        [ 9, 16],
        [25, 36]], dtype=torch.int32)

### 5. Reshape

In [11]:
#Same as pandas or numpy
new_torch_tensor=torch_tensor.reshape(-1)
print(new_torch_tensor)
print(torch_tensor)

tensor([ 1,  4,  9, 16, 25, 36], dtype=torch.int32)
tensor([[ 1,  4],
        [ 9, 16],
        [25, 36]], dtype=torch.int32)


In [12]:
#(수정예정)view is also same as reshape func, but the differance between these two is that view changes the shape of the original tensor and reshape doesn't
#contiguous+view=reshape
new_torch_tensor=torch_tensor.view(-1)
print(new_torch_tensor)
print(torch_tensor)

tensor([ 1,  4,  9, 16, 25, 36], dtype=torch.int32)
tensor([[ 1,  4],
        [ 9, 16],
        [25, 36]], dtype=torch.int32)


### 6. Slicing

In [13]:
#splitting data size for dimesion0
#if alpha%split!=0 just print the leftover at the last cell
#in this case 10%4==2
x=torch.FloatTensor(10,4)
splits=x.split(4,dim=0)
for i in splits:
    print(i.size())

torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([2, 4])


In [14]:
#chunk is different from split
#chunk uses the index to split into n dimension
#in this case 4 dimension
x=torch.FloatTensor(10,4)
splits=x.chunk(4,dim=0)
for i in splits:
    print(i.size())

torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([1, 4])


### 7. Indice_select

In [15]:
#(예정)

### 8. Cat

In [16]:
x=torch.FloatTensor([[1,2,3],
                   [4,5,6]])
y=torch.FloatTensor([[7,8,9],[10,11,12]])
z=torch.cat([x,y],dim=0)
print(x.size())
print(y.size())
print(z)
print(z.size())

torch.Size([2, 3])
torch.Size([2, 3])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
torch.Size([4, 3])


### 9. Stack

In [17]:
z=torch.stack([x,y],dim=0)
print(x.size())
print(y.size())
print(z)
print(z.size())

torch.Size([2, 3])
torch.Size([2, 3])
tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])
torch.Size([2, 2, 3])


In [18]:
z=torch.stack([x,y],dim=-1)
print(x.size())
print(y.size())
print(z)
print(z.size())

torch.Size([2, 3])
torch.Size([2, 3])
tensor([[[ 1.,  7.],
         [ 2.,  8.],
         [ 3.,  9.]],

        [[ 4., 10.],
         [ 5., 11.],
         [ 6., 12.]]])
torch.Size([2, 3, 2])


In [19]:
#useful situation for y(hat)
result=[]
for i in range(5):
    x=torch.FloatTensor(2,2)
    result+=[x]
print(result)
result=torch.stack(result)
result.size()

[tensor([[1.0000e+00, 4.5916e-41],
        [0.0000e+00, 0.0000e+00]]), tensor([[1.4013e-45, 2.6250e+00],
        [1.8982e-29, 4.5916e-41]]), tensor([[1.8515e-29, 4.5916e-41],
        [0.0000e+00, 0.0000e+00]]), tensor([[2.3694e-38, 2.3694e-38],
        [1.8982e-29, 4.5916e-41]]), tensor([[0.0000, 2.6250],
        [0.0000, 0.0000]])]


torch.Size([5, 2, 2])

### 10. Expand

In [20]:
x=torch.FloatTensor([[[1,2]],[[3,4]]])
print(x.size())

torch.Size([2, 1, 2])


In [21]:
y=x.expand(*[2,3,2])
print(y.size())
print(y)

torch.Size([2, 3, 2])
tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])


#### Using cat

In [22]:
y=torch.cat([x,x,x],dim=1)
print(y.size())
print(y)

torch.Size([2, 3, 2])
tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])


### 11. Max

In [23]:
x=torch.randperm(3**3) #(27,1)
x=x.reshape([3,3,-1])
x

tensor([[[ 7,  6, 18],
         [11,  9,  4],
         [24,  5, 20]],

        [[23,  0, 10],
         [26, 14, 22],
         [ 1, 16, 25]],

        [[ 2,  8,  3],
         [15, 21, 19],
         [12, 13, 17]]])

In [24]:
#shows the larget index of the according dim
y=x.argmax(dim=1)
y

tensor([[2, 1, 2],
        [1, 2, 2],
        [1, 1, 1]])

In [25]:
#topK shows the largest value and index of the array
values,indices=torch.topk(x,dim=1,k=1)
print(values.size())
print(indices.size())

torch.Size([3, 1, 3])
torch.Size([3, 1, 3])


In [29]:
print(indices.squeeze(dim=1).size())
print(indices.squeeze(dim=1))

torch.Size([3, 3])
tensor([[2, 1, 2],
        [1, 2, 2],
        [1, 1, 1]])


### 13. Maskfill

In [32]:
#when the mask is true then fill the values with the value
m=x>4
y=x.masked_fill(m,value=-1)
y

tensor([[[-1, -1, -1],
         [-1, -1,  4],
         [-1, -1, -1]],

        [[-1,  0, -1],
         [-1, -1, -1],
         [ 1, -1, -1]],

        [[ 2, -1,  3],
         [-1, -1, -1],
         [-1, -1, -1]]])